### ISSUE TITLE
Project fails to build when using Light2D

### ISSUE THREAD

**Issue by MrLeebo** [SSS135/Light2D#3]
Starting a brand new unity project with Light2D imported fails to build with multiple compiler errors. This is on a Macbook Pro running Unity 5.6.1f1 Personal (64bit).

REPRO:

1. Start a new unity project
2. From the asset store, install Light2D (Free version)
3. To confirm the install succeeded, open the Rocket scene and Play it
4. Try to Build & Run the project

EXPECTED:

<img width="463" alt="screen shot 2017-06-23 at 11 35 17 pm" src="https://user-images.githubusercontent.com/2754163/27505741-a830e78c-586c-11e7-83fb-db7302f0bc21.png">

ACTUAL:

<img width="942" alt="screen shot 2017-06-23 at 11 30 44 pm" src="https://user-images.githubusercontent.com/2754163/27505718-2d3150bc-586c-11e7-8bbb-97da8c91c398.png">

RESOLUTION:

I was able to get the build to succeed by deleting the `using UnityEditor;` line from **LightingSystem.cs** and deleting **LightAuto.shader**.

**Comment by zerodarkzone** [comment]
I was just going to respond exactly with what you did. I'm glad you figured out

**Comment by MrLeebo** [comment]
I've lost interest in this.
